baseURL = 'https://orion551.github.io/itcorner/'
languageCode = 'it-IT'
title = 'CISF26'
theme = 'cisf26-theme'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menus.main]]
  name = "Home"
  url = "/"
  weight = 10
[[menus.main]]
  name = "Chi Siamo"
  url = "/about-us/"
  weight = 20
[[menus.main]]
  name = "Strutture"
  url = "/locations/"
  weight = 30
[[menus.main]]
  name = "Ospiti"
  url = "/guests/"
  weight = 40
[[menus.main]]
  name = "Programma"
  url = "/schedule/"
  weight = 50
[[menus.main]]
  name = "Partners"
  url = "/partners/"
  weight = 60