baseURL = 'https://orion551.github.io/itcorner/'
languageCode = 'it-IT'
title = 'CISF26'
theme = 'cisf26-theme'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menus.main]]
  identifier = "home"
  name = "Home"
  pageRef = "/"
  weight = 10
[[menus.main]]
  identifier = "about-us"
  name = "Chi Siamo"
  pageRef = "/about-us/"
  weight = 20
[[menus.main]]
  identifier = "locations"
  name = "Strutture"
  pageRef = "/locations/"
  weight = 30
[[menus.main]]
  identifier = "guests"
  name = "Ospiti"
  pageRef = "/guests/"
  weight = 40
[[menus.main]]
  identifier = "schedule"
  name = "Programma"
  pageRef = "/schedule/"
  weight = 50
[[menus.main]]
  identifier = "partners"
  name = "Partners"
  pageRef = "/partners/"
  weight = 60

[params]
  siteTitle = "CISF26"
  image = "images/cisf26-logo.png"
  alt = 'CISF26 Logo'