backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads"
public_folder: "/itcorner/images/uploads"
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Picture"
        name: "image"
        widget: "image"
  - name: "organizer"
    label: "Organizers"
    folder: "content/organizer"
    create: true
    slug: "{{slug}}"
    fields:
        - { label: "Name", name: "name", widget: "string" }
        - { label: "Role", name: "role", widget: "string" }
        - { label: "Description", name: "description", widget: "string" }
        - label: "Picture"
          name: "image"
          widget: "image"
          choose_url: false
          media_library:
            config:
              multiple: false
  - name: "event"
    label: "Events"
    folder: "content/scheduled-event"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Event Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Address", name: "address", widget: "string" }
      - label: "Day"
        name: "day"
        widget: "select"
        options:
          - { label: "Monday", value: "monday" }
          - { label: "Tuesday", value: "tuesday" }
          - { label: "Wednesday", value: "wednesday" }
          - { label: "Thursday", value: "thursday" }
          - { label: "Friday", value: "friday" }
          - { label: "Saturday", value: "saturday" }
          - { label: "Sunday", value: "sunday" }
      - { label: "Weight", name: "weight", widget: "number", default: 10, value_type: "int" }
      - label: "Picture"
        name: "coverImage"
        widget: "image"
        choose_url: false
        media_library:
          config:
            multiple: false
        required: false
      - { label: "Start Time", name: "start_time", widget: "datetime", format: "HH:mm", time_format: "HH:mm", date_format: false }
      - { label: "End Time", name: "end_time", widget: "datetime", format: "HH:mm", time_format: "HH:mm", date_format: false }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      # - { label: "Speaker", name: "speaker", widget: "string", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - label: "Speakers"
        name: "speakers"
        widget: "relation"
        collection: "guests"
        search_fields: [ "title" ]
        value_field: "{{slug}}"
        display_fields: [ "title" ]
        multiple: true
        required: false
      # Aggiungi il nuovo campo per selezionare il contesto
      - label: "Event Context"
        name: "context"
        widget: "relation"
        collection: "event_contexts"
        search_fields: [ "label" ]
        value_field: "name"
        display_fields: [ "label" ]
        required: false
        default: "all"
  - name: "guests"
    label: "Guests"
    folder: "content/guests"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Full Name", name: "title", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Biography", name: "bio", widget: "text" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - label: "Picture"
        name: "image"
        widget: "image"
        choose_url: false
        media_library:
          config:
            multiple: false
  - name: "event_contexts"
    label: "Event Contexts"
    folder: "content/contexts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Context Name", name: "title", widget: "string" }
