backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads"
public_folder: "/itcorner/images/uploads"
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "organizer"
    label: "Organizers"
    folder: "content/organizer"
    create: true
    slug: "{{slug}}"
    fields:
        - { label: "Name", name: "name", widget: "string" }
        - { label: "Role", name: "role", widget: "string" }